[project]
name = "megacode-sovereign-stack"
version = "0.1.0"
description = "Sovereign Monorepo for Mega Code"
dependencies = []

[tool.uv]
managed = true

[tool.uv.workspace]
members = ["apps/*", "packages/*"]

[tool.ruff]
line-length = 80
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "W", "I", "N", "UP", "B", "ANN"]
ignore = ["ANN101", "ANN102"]

[tool.ruff.lint.isort]
known-first-party = ["megacode-sovereign-stack"]
