/**
 * @license
 * Copyright 2025 Qwen Team
 * SPDX-License-Identifier: Apache-2.0
 */

export {
  DaemonClient,
  DaemonHttpError,
  isNonBlockingAccepted,
  matchTurnEvent,
  type CreateSessionRequest,
  type DaemonClientOptions,
  type NonBlockingPromptAccepted,
  type PromptRequest,
  type RestoreSessionRequest,
  type SubscribeOptions,
} from './DaemonClient.js';
// Transport abstraction layer
export { DaemonTransportClosedError } from './DaemonTransport.js';
export type {
  DaemonTransport,
  DaemonTransportFetchOptions,
  DaemonTransportSubscribeOptions,
  DaemonTransportType,
} from './DaemonTransport.js';
export type { RestSseTransport } from './RestSseTransport.js';
// negotiateTransport + the concrete ACP transport classes are intentionally
// NOT re-exported here: a static import chain from this barrel would pull
// their framing/SSE code into the budget-checked browser bundle (see
// `scripts/build.js` MAX_DAEMON_BROWSER_BUNDLE_BYTES). They ship instead
// behind the opt-in `@qwen-code/sdk/daemon/transports` subpath
// (`./transports.ts`), so REST-only consumers stay tree-shaken while
// consumers who want resumable ACP-over-HTTP get a first-class import:
//   import { negotiateTransport, AcpHttpTransport }
//     from '@qwen-code/sdk/daemon/transports';
// The `NegotiateTransportOptions` *type* stays available from this barrel
// for backward compatibility (type-only, no bundle cost).
export type { NegotiateTransportOptions } from './negotiateTransport.js';
export type { JsonRpcNotification } from './AcpEventDenormalizer.js';
export type { TransportFactory } from './AutoReconnectTransport.js';
export {
  DaemonAuthFlow,
  DEVICE_FLOW_EXPIRY_GRACE_MS,
  type AwaitCompletionOptions,
  type DaemonAuthFlowHandle,
} from './DaemonAuthFlow.js';
export {
  DaemonSessionClient,
  type DaemonReplaySnapshot,
  type DaemonSessionClientOptions,
  type DaemonSessionSubscribeOptions,
} from './DaemonSessionClient.js';
export {
  asKnownDaemonEvent,
  DAEMON_KNOWN_EVENT_TYPE_VALUES,
  MID_TURN_MESSAGE_INJECTED_EVENT,
  PENDING_PROMPT_ADDED_EVENT,
  PENDING_PROMPT_STARTED_EVENT,
  PENDING_PROMPT_COMPLETED_EVENT,
  createDaemonAuthState,
  createDaemonSessionViewState,
  isDaemonEventType,
  isKnownDaemonEvent,
  // Re-export the workspace-scoped budget event helper. Previously
  // the event JSDoc told consumers to use this helper to branch on
  // `scope === 'workspace'`, but the function lived in `events.ts`
  // and was never added to this barrel — SDK consumers had no public
  // import path. Now locked down by `daemon-public-surface.test.ts`.
  isWorkspaceScopedBudgetEvent,
  reduceDaemonAuthEvent,
  reduceDaemonAuthEvents,
  reduceDaemonSessionEvent,
  reduceDaemonSessionEvents,
} from './events.js';
export { parseSseStream, SseFramingError } from './sse.js';
export {
  appendLocalUserTranscriptMessage,
  createDaemonToolPreview,
  createDaemonTranscriptState,
  createDaemonTranscriptStore,
  DAEMON_PLAN_TOOL_CALL_ID,
  daemonBlockToHtml,
  daemonBlockToMarkdown,
  daemonBlockToPlainText,
  daemonToolPreviewToMarkdown,
  daemonUiEventToTerminalText,
  extractContentPart,
  formatBlockTimestamp,
  getOutputText as getDaemonUiOutputText,
  getSessionUpdatePayload,
  isDaemonUiSensitiveKey,
  isSubagentChildBlock,
  normalizeDaemonEvent,
  redactDaemonUiSensitiveFields,
  rebuildDaemonTranscriptBlockIndex,
  reduceDaemonTranscriptEvents,
  runAdapterConformanceSuite,
  sanitizeTerminalText as sanitizeDaemonTerminalText,
  selectApprovalMode,
  selectCurrentTool,
  selectLastFollowupSuggestion,
  selectPendingPermissionBlocks,
  selectSubagentChildBlocks,
  selectToolProgress,
  selectTranscriptBlocks,
  selectTranscriptBlocksOrderedByEventId,
  stringifyJson as stringifyDaemonUiJson,
  stripOscSequences as stripDaemonOscSequences,
  transcriptBlockToTerminalText,
  DAEMON_UI_CONFORMANCE_FIXTURES,
} from './ui/index.js';
export type {
  DaemonRenderOptions,
  DaemonHtmlRenderOptions,
  DaemonUiContentPart,
  DaemonUiAdapterUnderTest,
  DaemonUiConformanceFixture,
  ConformanceFailure,
  ConformanceSuiteResult,
  RunConformanceOptions,
} from './ui/index.js';
export type {
  DaemonShellTranscriptBlock,
  DaemonUserShellTranscriptBlock,
  DaemonPermissionTranscriptBlock,
  DaemonStatusTranscriptBlock,
  DaemonTextTranscriptBlock,
  DaemonToolPreview,
  DaemonToolTranscriptBlock,
  DaemonTranscriptBlock,
  DaemonTranscriptBlockKind,
  DaemonTranscriptQuestion,
  DaemonTranscriptQuestionOption,
  DaemonTranscriptReducerOptions,
  DaemonTranscriptSidechannelState,
  DaemonTranscriptState,
  DaemonTranscriptStore,
  DaemonUiAssistantDoneEvent,
  DaemonUiAuthDeviceFlowAuthorizedEvent,
  DaemonUiAuthDeviceFlowCancelledEvent,
  DaemonUiAuthDeviceFlowEvent,
  DaemonUiAuthDeviceFlowFailedEvent,
  DaemonUiAuthDeviceFlowStartedEvent,
  DaemonUiAuthDeviceFlowThrottledEvent,
  DaemonUiErrorEvent,
  DaemonUiEvent,
  DaemonUiEventBase,
  DaemonUiEventType,
  DaemonUiMcpBudgetWarningEvent,
  DaemonUiMcpChildRefusedEvent,
  DaemonUiMcpServerRestartedEvent,
  DaemonUiMcpServerRestartRefusedEvent,
  DaemonUiModelChangedEvent,
  DaemonUiPermissionOption,
  DaemonUiPermissionRequestEvent,
  DaemonUiPermissionResolvedEvent,
  DaemonUiSessionActions,
  DaemonUiSessionApprovalModeChangedEvent,
  DaemonUiSessionAvailableCommandsEvent,
  DaemonUiSessionMetadataChangedEvent,
  DaemonUiShellOutputEvent,
  DaemonUiStateResyncRequiredEvent,
  DaemonUiReplayCompleteEvent,
  DaemonUiPromptCancelledEvent,
  DaemonUiFollowupSuggestionEvent,
  DaemonUiStatusEvent,
  DaemonUiTextEvent,
  DaemonUiToolProvenance,
  DaemonUiToolUpdateEvent,
  DaemonUiWorkspaceAgentChangedEvent,
  DaemonUiWorkspaceInitializedEvent,
  DaemonUiWorkspaceMemoryChangedEvent,
  DaemonUiWorkspaceToolToggledEvent,
  NormalizeDaemonEventOptions,
} from './ui/index.js';
export {
  DAEMON_APPROVAL_MODES,
  DAEMON_ERROR_KINDS,
  DaemonCapabilityMissingError,
  isDaemonContentHash,
  requireWorkspaceCwd,
} from './types.js';
export type {
  DaemonAgentChangedData,
  DaemonAgentChangedEvent,
  DaemonApprovalModeChangedData,
  DaemonApprovalModeChangedEvent,
  DaemonClientEvictedData,
  DaemonClientEvictedEvent,
  DaemonControlEvent,
  // Daemon-emitted resync
  // signal for SSE reconnects past the ring eviction boundary.
  DaemonStateResyncRequiredData,
  DaemonStateResyncRequiredEvent,
  DaemonMcpServerAddedData,
  DaemonMcpServerAddedEvent,
  DaemonMcpServerRemovedData,
  DaemonMcpServerRemovedEvent,
  DaemonMcpServerRestartedData,
  DaemonMcpServerRestartedEvent,
  DaemonMcpServerRestartRefusedData,
  DaemonMcpServerRestartRefusedEvent,
  DaemonSessionRewoundData,
  DaemonSessionRewoundEvent,
  DaemonToolToggledData,
  DaemonToolToggledEvent,
  DaemonWorkspaceInitializedData,
  DaemonWorkspaceInitializedEvent,
  DaemonEventEnvelope,
  DaemonKnownEventType,
  // MCP guardrail push-event types. See `mcp_guardrail_events`
  // capability tag and the `DaemonMcpGuardrailEvent` union below.
  DaemonMcpBudgetWarningData,
  DaemonMcpBudgetWarningEvent,
  DaemonMcpChildRefusedBatchData,
  DaemonMcpChildRefusedBatchEvent,
  DaemonMcpGuardrailEvent,
  DaemonMcpRefusedServer,
  DaemonFileMemoryChangedData,
  DaemonManagedMemoryChangedData,
  DaemonMemoryChangedData,
  DaemonMemoryChangedEvent,
  DaemonModelSwitchedData,
  DaemonModelSwitchedEvent,
  DaemonModelSwitchFailedData,
  DaemonModelSwitchFailedEvent,
  DaemonPermissionOption,
  DaemonPermissionAlreadyResolvedData,
  DaemonPermissionAlreadyResolvedEvent,
  // Multi-client permission coordination push events.
  DaemonPermissionForbiddenData,
  DaemonPermissionForbiddenEvent,
  DaemonPermissionPartialVoteData,
  DaemonPermissionPartialVoteEvent,
  DaemonPermissionRequestData,
  DaemonPermissionRequestEvent,
  DaemonPermissionResolvedData,
  DaemonPermissionResolvedEvent,
  DaemonSessionClosedData,
  DaemonSessionClosedEvent,
  DaemonSessionClosedReason,
  DaemonSessionDiedData,
  DaemonSessionDiedEvent,
  DaemonSessionEvent,
  DaemonSessionMetadataUpdatedData,
  DaemonSessionMetadataUpdatedEvent,
  DaemonMidTurnMessageInjectedData,
  DaemonMidTurnMessageInjectedEvent,
  DaemonPendingPromptAddedData,
  DaemonPendingPromptAddedEvent,
  DaemonPendingPromptStartedData,
  DaemonPendingPromptStartedEvent,
  DaemonPendingPromptCompletedData,
  DaemonPendingPromptCompletedEvent,
  DaemonPendingPromptEvent,
  DaemonSessionUpdateData,
  DaemonSessionUpdateEvent,
  DaemonSessionViewState,
  DaemonSlowClientWarningData,
  DaemonSlowClientWarningEvent,
  DaemonStreamErrorData,
  DaemonStreamErrorEvent,
  DaemonStreamLifecycleEvent,
  DaemonWorkspaceMutationEvent,
  DaemonAuthDeviceFlowProviderId,
  DaemonAuthDeviceFlowStatus,
  DaemonAuthDeviceFlowErrorKind,
  DaemonAuthDeviceFlowStartedData,
  DaemonAuthDeviceFlowStartedEvent,
  DaemonAuthDeviceFlowThrottledData,
  DaemonAuthDeviceFlowThrottledEvent,
  DaemonAuthDeviceFlowAuthorizedData,
  DaemonAuthDeviceFlowAuthorizedEvent,
  DaemonAuthDeviceFlowFailedData,
  DaemonAuthDeviceFlowFailedEvent,
  DaemonAuthDeviceFlowCancelledData,
  DaemonAuthDeviceFlowCancelledEvent,
  DaemonAuthEvent,
  // Daemon assist push (server-side ghost-text suggestion)
  DaemonAssistEvent,
  DaemonFollowupSuggestionData,
  DaemonFollowupSuggestionEvent,
  // Non-blocking prompt completion events
  DaemonTurnEvent,
  DaemonTurnCompleteData,
  DaemonTurnCompleteEvent,
  DaemonTurnErrorData,
  DaemonTurnErrorEvent,
  DaemonDeviceFlowReducerState,
  DaemonAuthState,
  KnownDaemonEvent,
} from './events.js';
export type {
  DaemonAgentLevel,
  DaemonAgentMutationResult,
  DaemonGeneratedAgentContent,
  DaemonApprovalMode,
  DaemonApprovalModeResult,
  DaemonInitWorkspaceResult,
  DaemonMcpManageAction,
  DaemonMcpManageResult,
  DaemonMcpRestartResult,
  DaemonRewindResult,
  DaemonRewindSnapshotInfo,
  DaemonSessionBtwResult,
  DaemonMidTurnMessageResult,
  DaemonPendingPromptSummary,
  DaemonPendingPromptsResult,
  DaemonRemovePendingPromptResult,
  DaemonSessionRecapResult,
  DaemonShellCommandResult,
  DaemonRuntimeMcpAddRequest,
  DaemonRuntimeMcpAddResult,
  DaemonRuntimeMcpRemoveResult,
  DaemonToolToggleResult,
  DaemonSettingDescriptor,
  DaemonWorkspaceSettingsStatus,
  DaemonSettingUpdateResult,
  DaemonAvailableCommand,
  DaemonArchiveSessionsResult,
  DaemonCapabilities,
  DaemonContextCategoryBreakdown,
  DaemonContextFileScope,
  DaemonContextMemoryDetail,
  DaemonContextSkillDetail,
  DaemonContextToolDetail,
  DaemonCreateAgentRequest,
  DaemonEnvCell,
  DaemonEnvKind,
  DaemonErrorKind,
  DaemonEvent,
  DaemonMcpDiscoveryState,
  DaemonMcpServerRuntimeStatus,
  DaemonMcpTransport,
  DaemonMode,
  DaemonProtocolVersions,
  DaemonRestoredSession,
  DaemonSession,
  DaemonSessionArchiveState,
  DaemonAuthProviderId,
  DaemonAuthDeviceFlowSdkStatus,
  DaemonAuthDeviceFlowSdkErrorKind,
  DaemonAuthProviderStatus,
  DaemonAuthStatusSnapshot,
  DaemonDeviceFlowStartResult,
  DaemonDeviceFlowState,
  DaemonSessionContextStatus,
  DaemonSessionAgentTaskStatus,
  DaemonSessionMonitorTaskStatus,
  DaemonSessionProcessTaskLifecycleStatus,
  DaemonSessionContextUsage,
  DaemonSessionContextUsageStatus,
  DaemonSessionState,
  DaemonSessionSummary,
  DaemonSessionShellTaskStatus,
  DaemonSessionSupportedCommandsStatus,
  DaemonSessionTaskLifecycleStatus,
  DaemonSessionTaskStatus,
  DaemonSessionTasksStatus,
  DaemonSessionStatsStatus,
  DaemonSessionStatsModelMetrics,
  DaemonSessionStatsToolByName,
  DaemonSkillLevel,
  DaemonPreflightCell,
  DaemonPreflightKind,
  DaemonStatus,
  DaemonStatusCell,
  DaemonUpdateAgentRequest,
  DaemonContentHash,
  DaemonWorkspaceAgentDetail,
  DaemonWorkspaceAgentSummary,
  DaemonWorkspaceAgentsStatus,
  DaemonWorkspaceEnvStatus,
  DaemonWorkspaceFile,
  DaemonWorkspaceFileBytes,
  DaemonWorkspaceFileEditRequest,
  DaemonWorkspaceFileEditResult,
  DaemonWorkspaceFileWriteRequest,
  DaemonWorkspaceFileWriteResult,
  DaemonWorkspaceMcpServerStatus,
  DaemonWorkspaceMcpStatus,
  DaemonWorkspaceMcpToolStatus,
  DaemonWorkspaceMcpToolsStatus,
  DaemonWorkspaceMcpResourceStatus,
  DaemonWorkspaceMcpResourcesStatus,
  DaemonWorkspaceMemoryFile,
  DaemonWorkspaceMemoryStatus,
  DaemonWorkspaceMemoryRememberContextMode,
  DaemonWorkspaceMemoryRememberOptions,
  DaemonWorkspaceMemoryRememberResult,
  DaemonWorkspaceMemoryRememberTask,
  DaemonWorkspaceMemoryRememberTaskStatus,
  DaemonWorkspacePreflightStatus,
  DaemonWorkspaceProviderCurrent,
  DaemonWorkspaceProviderModel,
  DaemonWorkspaceProviderStatus,
  DaemonWorkspaceProvidersStatus,
  DaemonWorkspaceSkillStatus,
  DaemonWorkspaceSkillsStatus,
  DaemonWorkspaceToolStatus,
  DaemonWorkspaceToolsStatus,
  DaemonWriteMemoryRequest,
  DaemonWriteMemoryResult,
  DaemonUnarchiveSessionsResult,
  DaemonCommandHookConfig,
  DaemonFunctionHookConfig,
  DaemonHookConfig,
  DaemonHookEntry,
  DaemonHookEventMeta,
  DaemonHookEventName,
  DaemonHookMatcherKind,
  DaemonHookSource,
  DaemonHttpHookConfig,
  DaemonPromptHookConfig,
  DaemonSessionHooksStatus,
  DaemonUnknownHookConfig,
  DaemonWorkspaceHooksStatus,
  DaemonExtensionInstallType,
  DaemonExtensionOriginSource,
  DaemonExtensionCapabilities,
  DaemonExtensionEntry,
  DaemonWorkspaceExtensionsStatus,
  HeartbeatResult,
  MCPServerConfigShape,
  PermissionOutcome,
  PermissionOutcomeCancelled,
  PermissionOutcomeSelected,
  PermissionResponse,
  PromptContentBlock,
  PromptResult,
  PromptTextContent,
  SetModelResult,
  SessionMetadataResult,
} from './types.js';
